name: Build TrollStoreJitEnabler

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "export THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "export THEOS_MAKE_PATH=$HOME/theos/makefiles" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        brew install llvm ldid
        sudo gem install xcpretty

    - name: Build project
      env:
        THEOS: ${{ env.THEOS }}
        THEOS_MAKE_PATH: ${{ env.THEOS }}/makefiles
      run: |
        export THEOS=${{ env.THEOS }}
        export THEOS_MAKE_PATH=${{ env.THEOS }}/makefiles
        make

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build-Output
        path: .theos/obj/**/*.dylib
